/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KeyId = IDL.Nat;
export const RequestId = IDL.Nat;
export const KeyStatus = IDL.Variant({
  'active' : IDL.Null,
  'returned' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Key = IDL.Record({
  'id' : KeyId,
  'tag' : IDL.Text,
  'status' : KeyStatus,
  'owner' : IDL.Principal,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
});
export const ReturnRequest = IDL.Record({
  'id' : RequestId,
  'finderName' : IDL.Text,
  'createdAt' : Timestamp,
  'finderContact' : IDL.Text,
  'keyId' : KeyId,
  'dismissed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createKey' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [KeyId], []),
  'deleteKey' : IDL.Func([KeyId], [IDL.Bool], []),
  'dismissReturnRequest' : IDL.Func([RequestId], [IDL.Bool], []),
  'getKey' : IDL.Func([KeyId], [IDL.Opt(Key)], ['query']),
  'getReturnRequestCount' : IDL.Func([KeyId], [IDL.Nat], []),
  'listKeys' : IDL.Func([], [IDL.Vec(Key)], ['query']),
  'listReturnRequests' : IDL.Func([KeyId], [IDL.Vec(ReturnRequest)], []),
  'markKeyReturned' : IDL.Func([KeyId], [IDL.Bool], []),
  'submitReturnRequest' : IDL.Func(
      [KeyId, IDL.Text, IDL.Text],
      [IDL.Opt(RequestId)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KeyId = IDL.Nat;
  const RequestId = IDL.Nat;
  const KeyStatus = IDL.Variant({ 'active' : IDL.Null, 'returned' : IDL.Null });
  const Timestamp = IDL.Int;
  const Key = IDL.Record({
    'id' : KeyId,
    'tag' : IDL.Text,
    'status' : KeyStatus,
    'owner' : IDL.Principal,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
  });
  const ReturnRequest = IDL.Record({
    'id' : RequestId,
    'finderName' : IDL.Text,
    'createdAt' : Timestamp,
    'finderContact' : IDL.Text,
    'keyId' : KeyId,
    'dismissed' : IDL.Bool,
  });
  
  return IDL.Service({
    'createKey' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [KeyId], []),
    'deleteKey' : IDL.Func([KeyId], [IDL.Bool], []),
    'dismissReturnRequest' : IDL.Func([RequestId], [IDL.Bool], []),
    'getKey' : IDL.Func([KeyId], [IDL.Opt(Key)], ['query']),
    'getReturnRequestCount' : IDL.Func([KeyId], [IDL.Nat], []),
    'listKeys' : IDL.Func([], [IDL.Vec(Key)], ['query']),
    'listReturnRequests' : IDL.Func([KeyId], [IDL.Vec(ReturnRequest)], []),
    'markKeyReturned' : IDL.Func([KeyId], [IDL.Bool], []),
    'submitReturnRequest' : IDL.Func(
        [KeyId, IDL.Text, IDL.Text],
        [IDL.Opt(RequestId)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };