/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Key {
  'id' : KeyId,
  'tag' : string,
  'status' : KeyStatus,
  'owner' : Principal,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'updatedAt' : Timestamp,
}
export type KeyId = bigint;
export type KeyStatus = { 'active' : null } |
  { 'returned' : null };
export type RequestId = bigint;
export interface ReturnRequest {
  'id' : RequestId,
  'finderName' : string,
  'createdAt' : Timestamp,
  'finderContact' : string,
  'keyId' : KeyId,
  'dismissed' : boolean,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'createKey' : ActorMethod<[string, [] | [string]], KeyId>,
  'deleteKey' : ActorMethod<[KeyId], boolean>,
  'dismissReturnRequest' : ActorMethod<[RequestId], boolean>,
  'getKey' : ActorMethod<[KeyId], [] | [Key]>,
  'getReturnRequestCount' : ActorMethod<[KeyId], bigint>,
  'listKeys' : ActorMethod<[], Array<Key>>,
  'listReturnRequests' : ActorMethod<[KeyId], Array<ReturnRequest>>,
  'markKeyReturned' : ActorMethod<[KeyId], boolean>,
  'submitReturnRequest' : ActorMethod<
    [KeyId, string, string],
    [] | [RequestId]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];