/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type RequestId = bigint;
export interface ReturnRequest {
    id: RequestId;
    finderName: string;
    createdAt: Timestamp;
    finderContact: string;
    keyId: KeyId;
    dismissed: boolean;
}
export type KeyId = bigint;
export interface Key {
    id: KeyId;
    tag: string;
    status: KeyStatus;
    owner: Principal;
    createdAt: Timestamp;
    description?: string;
    updatedAt: Timestamp;
}
export enum KeyStatus {
    active = "active",
    returned = "returned"
}
export interface backendInterface {
    createKey(tag: string, description: string | null): Promise<KeyId>;
    deleteKey(keyId: KeyId): Promise<boolean>;
    dismissReturnRequest(requestId: RequestId): Promise<boolean>;
    getKey(keyId: KeyId): Promise<Key | null>;
    getReturnRequestCount(keyId: KeyId): Promise<bigint>;
    listKeys(): Promise<Array<Key>>;
    listReturnRequests(keyId: KeyId): Promise<Array<ReturnRequest>>;
    markKeyReturned(keyId: KeyId): Promise<boolean>;
    submitReturnRequest(keyId: KeyId, finderName: string, finderContact: string): Promise<RequestId | null>;
}
import type { Key as _Key, KeyId as _KeyId, KeyStatus as _KeyStatus, RequestId as _RequestId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createKey(arg0: string, arg1: string | null): Promise<KeyId> {
        if (this.processError) {
            try {
                const result = await this.actor.createKey(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createKey(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteKey(arg0: KeyId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKey(arg0);
            return result;
        }
    }
    async dismissReturnRequest(arg0: RequestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissReturnRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissReturnRequest(arg0);
            return result;
        }
    }
    async getKey(arg0: KeyId): Promise<Key | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKey(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKey(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReturnRequestCount(arg0: KeyId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReturnRequestCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReturnRequestCount(arg0);
            return result;
        }
    }
    async listKeys(): Promise<Array<Key>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKeys();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKeys();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReturnRequests(arg0: KeyId): Promise<Array<ReturnRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReturnRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReturnRequests(arg0);
            return result;
        }
    }
    async markKeyReturned(arg0: KeyId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markKeyReturned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markKeyReturned(arg0);
            return result;
        }
    }
    async submitReturnRequest(arg0: KeyId, arg1: string, arg2: string): Promise<RequestId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReturnRequest(arg0, arg1, arg2);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReturnRequest(arg0, arg1, arg2);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_KeyStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KeyStatus): KeyStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Key_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Key): Key {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Key]): Key | null {
    return value.length === 0 ? null : from_candid_Key_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RequestId]): RequestId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _KeyId;
    tag: string;
    status: _KeyStatus;
    owner: Principal;
    createdAt: _Timestamp;
    description: [] | [string];
    updatedAt: _Timestamp;
}): {
    id: KeyId;
    tag: string;
    status: KeyStatus;
    owner: Principal;
    createdAt: Timestamp;
    description?: string;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        tag: value.tag,
        status: from_candid_KeyStatus_n5(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.description)),
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    returned: null;
}): KeyStatus {
    return "active" in value ? KeyStatus.active : "returned" in value ? KeyStatus.returned : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Key>): Array<Key> {
    return value.map((x)=>from_candid_Key_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
